server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: classpath:routes.yaml


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: gateway
