spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
              - Path=/notifications/**
