server:
  port: 8083

spring:
  application:
    name: payment-service

logging:
  level:
    root: INFO
    com.ecommerce.payment: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
custom:
  user-service-url: http://localhost:8080/users

